# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '新闻眼' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 新闻眼

  target '新闻眼Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '新闻眼UITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'BmobSDK'
    pod 'AFNetworking', '~> 3.0'
    pod 'SVPullToRefresh'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SDWebImage', '~>3.8'
    pod'JSONModel'
  end

end
